import { DeliveryCostService } from './services/DeliveryCostService';
// generated by LLM
/**
 * Client demo for Delivery Cost Tracking System
 * Demonstrates all the required functionality and additional features
 */
class DeliveryCostClient {
  private service: DeliveryCostService;

  constructor() {
    this.service = DeliveryCostService.getInstance();
  }

  /**
   * Demo 1: Basic functionality required by the question
   */
  async demoBasicFunctionality(): Promise<void> {
    console.log('\n🚀 === DEMO 1: BASIC FUNCTIONALITY ===');
    console.log('Testing the 3 main methods required by the question:\n');

    try {
      // 1. Add drivers with different hourly rates
      console.log('1️⃣ Adding drivers...');
      await this.service.addDriver('driver_001', 15.00);  // $15/hour
      await this.service.addDriver('driver_002', 20.00);  // $20/hour
      await this.service.addDriver('driver_003', 12.50);  // $12.50/hour

      // 2. Record deliveries
      console.log('\n2️⃣ Recording deliveries...');
      
      // Delivery 1: 1.5 hours = $22.50
      const start1 = new Date('2024-01-15T10:00:00Z');
      const end1 = new Date('2024-01-15T11:30:00Z');
      await this.service.recordDelivery('driver_001', start1, end1);

      // Delivery 2: 2 hours = $40.00
      const start2 = new Date('2024-01-15T12:00:00Z');
      const end2 = new Date('2024-01-15T14:00:00Z');
      await this.service.recordDelivery('driver_002', start2, end2);

      // Delivery 3: 0.75 hours = $9.38
      const start3 = new Date('2024-01-15T15:00:00Z');
      const end3 = new Date('2024-01-15T15:45:00Z');
      await this.service.recordDelivery('driver_003', start3, end3);

      // 3. Calculate total cost
      console.log('\n3️⃣ Calculating total cost...');
      const totalCost = await this.service.fetchTotalCostIncurredForAllDeliveries();
      
      console.log(`\n✅ Basic functionality test completed!`);
      console.log(`📊 Expected total: $22.50 + $40.00 + $9.38 = $71.88`);
      console.log(`💰 Actual total: $${totalCost.toFixed(2)}`);

    } catch (error) {
      console.error('❌ Error in basic functionality demo:', error);
    }
  }

  /**
   * Demo 2: Advanced features and edge cases
   */
  async demoAdvancedFeatures(): Promise<void> {
    console.log('\n🚀 === DEMO 2: ADVANCED FEATURES ===');
    console.log('Testing additional functionality and edge cases:\n');

    try {
      // Test concurrent deliveries for same driver
      console.log('🔄 Testing concurrent deliveries for same driver...');
      
      const driverId = 'driver_001';
      const baseTime = new Date('2024-01-16T09:00:00Z');
      
      // Multiple simultaneous deliveries
      const deliveries = [
        { start: new Date(baseTime.getTime()), end: new Date(baseTime.getTime() + 60 * 60 * 1000) }, // 1 hour
        { start: new Date(baseTime.getTime() + 30 * 60 * 1000), end: new Date(baseTime.getTime() + 90 * 60 * 1000) }, // 1 hour, 30 min overlap
        { start: new Date(baseTime.getTime() + 60 * 60 * 1000), end: new Date(baseTime.getTime() + 120 * 60 * 1000) } // 1 hour, no overlap
      ];

      for (const delivery of deliveries) {
        await this.service.recordDelivery(driverId, delivery.start, delivery.end);
      }

      // Test driver rate updates
      console.log('\n💰 Testing driver rate updates...');
      await this.service.updateDriverRate('driver_002', 25.00);
      
      // Test cost calculations
      console.log('\n🧮 Testing various cost calculations...');
      
      const driverCost = await this.service.calculateCostForDriver('driver_001');
      console.log(`Cost for driver_001: $${driverCost.toFixed(2)}`);

      const dateRangeCost = await this.service.calculateCostForDateRange(
        new Date('2024-01-15T00:00:00Z'),
        new Date('2024-01-15T23:59:59Z')
      );
      console.log(`Cost for Jan 15, 2024: $${dateRangeCost.toFixed(2)}`);

      // Test system stats
      console.log('\n📊 Testing system statistics...');
      const stats = await this.service.getSystemStats();
      console.log('System Statistics:', stats);

    } catch (error) {
      console.error('❌ Error in advanced features demo:', error);
    }
  }

  /**
   * Demo 3: Error handling and validation
   */
  async demoErrorHandling(): Promise<void> {
    console.log('\n🚀 === DEMO 3: ERROR HANDLING ===');
    console.log('Testing error handling and validation:\n');

    try {
      // Test invalid driver ID
      console.log('❌ Testing invalid driver ID...');
      try {
        await this.service.recordDelivery('', new Date(), new Date());
      } catch (error) {
        const errorMessage = error instanceof Error ? error.message : String(error);
        console.log('✅ Caught error:', errorMessage);
      }

      // Test invalid time range
      console.log('\n❌ Testing invalid time range...');
      try {
        const futureTime = new Date();
        futureTime.setHours(futureTime.getHours() + 1);
        await this.service.recordDelivery('driver_001', futureTime, new Date());
      } catch (error) {
        const errorMessage = error instanceof Error ? error.message : String(error);
        console.log('✅ Caught error:', errorMessage);
      }

      // Test non-existent driver
      console.log('\n❌ Testing non-existent driver...');
      try {
        await this.service.recordDelivery('non_existent', new Date(), new Date());
      } catch (error) {
        const errorMessage = error instanceof Error ? error.message : String(error);
        console.log('✅ Caught error:', errorMessage);
      }

      // Test invalid hourly rate
      console.log('\n❌ Testing invalid hourly rate...');
      try {
        await this.service.addDriver('driver_004', -5.00);
      } catch (error) {
        const errorMessage = error instanceof Error ? error.message : String(error);
        console.log('✅ Caught error:', errorMessage);
      }

    } catch (error) {
      console.error('❌ Error in error handling demo:', error);
    }
  }

  /**
   * Demo 4: Performance and concurrent access
   */
  async demoConcurrentAccess(): Promise<void> {
    console.log('\n🚀 === DEMO 4: CONCURRENT ACCESS ===');
    console.log('Testing concurrent operations and performance:\n');

    try {
      // Add multiple drivers concurrently
      console.log('🔄 Adding multiple drivers concurrently...');
      const driverPromises = [];
      
      for (let i = 1; i <= 10; i++) {
        driverPromises.push(
          this.service.addDriver(`concurrent_driver_${i}`, 15.00 + i)
        );
      }

      await Promise.all(driverPromises);
      console.log('✅ Added 10 drivers concurrently');

      // Record multiple deliveries concurrently
      console.log('\n🔄 Recording multiple deliveries concurrently...');
      const deliveryPromises = [];
      const baseTime = new Date('2024-01-17T10:00:00Z');
      
      for (let i = 1; i <= 5; i++) {
        const start = new Date(baseTime.getTime() + i * 60 * 60 * 1000);
        const end = new Date(start.getTime() + 30 * 60 * 1000); // 30 min delivery
        deliveryPromises.push(
          this.service.recordDelivery(`concurrent_driver_${i}`, start, end)
        );
      }

      await Promise.all(deliveryPromises);
      console.log('✅ Recorded 5 deliveries concurrently');

      // Test concurrent cost calculations
      console.log('\n🔄 Testing concurrent cost calculations...');
      const costPromises = [
        this.service.calculateCostForDriver('concurrent_driver_1'),
        this.service.calculateCostForDriver('concurrent_driver_2'),
        this.service.calculateTotalCostForAllDeliveries()
      ];

      const [cost1, cost2, totalCost] = await Promise.all(costPromises);
      console.log(`✅ Concurrent calculations completed:`);
      console.log(`   Driver 1 cost: $${cost1?.toFixed(2) || '0.00'}`);
      console.log(`   Driver 2 cost: $${cost2?.toFixed(2) || '0.00'}`);
      console.log(`   Total cost: $${totalCost?.toFixed(2) || '0.00'}`);

    } catch (error) {
      console.error('❌ Error in concurrent access demo:', error);
    }
  }

  /**
   * Run all demos
   */
  async runAllDemos(): Promise<void> {
    console.log('🚚 DELIVERY COST TRACKING SYSTEM DEMO');
    console.log('=====================================\n');

    try {
      await this.demoBasicFunctionality();
      await this.demoAdvancedFeatures();
      await this.demoErrorHandling();
      await this.demoConcurrentAccess();

      console.log('\n🎉 All demos completed successfully!');
      console.log('\n📋 SUMMARY OF IMPLEMENTED FEATURES:');
      console.log('✅ addDriver(driver_id, pay_per_hour)');
      console.log('✅ recordDelivery(driver_id, start_time, end_time)');
      console.log('✅ fetchTotalCostIncurredForAllDeliveries()');
      console.log('✅ Thread-safe concurrent operations');
      console.log('✅ Comprehensive error handling');
      console.log('✅ SOLID principles implementation');
      console.log('✅ Design patterns (Singleton, Strategy)');
      console.log('✅ Extensible and maintainable architecture');

    } catch (error) {
      console.error('❌ Error running demos:', error);
    }
  }
}

// Run the demo
const client = new DeliveryCostClient();
client.runAllDemos().catch(console.error);
